# Using golangci-lint
# https://golangci-lint.run

run:
  # Don't check test files
  tests: false
  skip-dirs:
    - testutils
    - .github
  # Use above settings for skip dirs
  skip-dirs-use-default: false
  # Run parallel linters. This might be too demanding, so in that case set to false
  allow-parallel-runners: true

# Output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
